version: "3"

services:
  profile-service:
    build: ./services/profile
    image: profile-service
    container_name: profile-service
    restart: always
    depends_on:
      - profile-db
    ports:
      - 8080:8080
    networks:
      - backend
  profile-db:
    image: postgres:13-alpine
    container_name: profile-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: profile
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
    