version: "3"

services:
  profile-service:
    build: 
      context: .
      dockerfile: ./services/profile/Dockerfile
    image: profile-service
    container_name: profile-service
    restart: always
    depends_on:
      - profile-db
    ports:
      - ${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}
    networks:
      - backend
  profile-db:
    image: postgres:13-alpine
    container_name: profile-db
    restart: always
    env_file:
      - ./services/profile/configs/config.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  gateway:
    build: 
      context: .
      dockerfile: ./gateway/Dockerfile
    image: gateway
    container_name: gateway
    restart: always
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
    