// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "in-backend/services/profile/models"

	mock "github.com/stretchr/testify/mock"
)

// HubbedLearnProvider is an autogenerated mock type for the HubbedLearnProvider type
type HubbedLearnProvider struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: c
func (_m *HubbedLearnProvider) CreateUser(c *models.Candidate) (*string, error) {
	ret := _m.Called(c)

	var r0 *string
	if rf, ok := ret.Get(0).(func(*models.Candidate) *string); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Candidate) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
