// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "in-backend/services/profile/models"

	mock "github.com/stretchr/testify/mock"
)

// KlentyProvider is an autogenerated mock type for the KlentyProvider type
type KlentyProvider struct {
	mock.Mock
}

// CreateProspect provides a mock function with given fields: c, pw
func (_m *KlentyProvider) CreateProspect(c *models.Candidate, pw string) error {
	ret := _m.Called(c, pw)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Candidate, string) error); ok {
		r0 = rf(c, pw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartCadence provides a mock function with given fields: email
func (_m *KlentyProvider) StartCadence(email string) error {
	ret := _m.Called(email)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProspect provides a mock function with given fields: c
func (_m *KlentyProvider) UpdateProspect(c *models.Candidate) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Candidate) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
